version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_jesus1
    environment:  
      - POSTGRES_DB=postgresDB1
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminJesus1
    ports:
      - "81:81"
    environment:
      PGADMIN_DEFAULT_EMAIL: jesus.pujada@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: